# Generated by Django 2.2.12 on 2021-03-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('manual_time', models.PositiveIntegerField()),
                ('required_time', models.PositiveIntegerField()),
                ('operating_time', models.PositiveIntegerField()),
            ],
        ),
    ]
