# Generated by Django 2.2.12 on 2021-03-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_arm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('manual_time', models.PositiveIntegerField()),
                ('required_time', models.PositiveIntegerField()),
                ('operating_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('manual_time', models.PositiveIntegerField()),
                ('required_time', models.PositiveIntegerField()),
                ('operating_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Arm',
        ),
    ]
