# Generated by Django 2.2.12 on 2021-03-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210316_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixarm',
            old_name='index',
            new_name='indeksi',
        ),
        migrations.RenameField(
            model_name='fixarm',
            old_name='manual_time',
            new_name='konevaiheen_ptuus',
        ),
        migrations.RenameField(
            model_name='fixarm',
            old_name='operating_time',
            new_name='purkuvaiheen_pituus',
        ),
        migrations.RenameField(
            model_name='fixarm',
            old_name='required_time',
            new_name='purun_aikatarve',
        ),
        migrations.RenameField(
            model_name='indarm',
            old_name='index',
            new_name='indeksi',
        ),
        migrations.RenameField(
            model_name='indarm',
            old_name='manual_time',
            new_name='konevaiheen_ptuus',
        ),
        migrations.RenameField(
            model_name='indarm',
            old_name='operating_time',
            new_name='purkuvaiheen_pituus',
        ),
        migrations.RenameField(
            model_name='indarm',
            old_name='required_time',
            new_name='purun_aikatarve',
        ),
    ]
