# Generated by Django 2.2.12 on 2021-03-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210316_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndArm',
            new_name='Arm2300',
        ),
        migrations.RenameModel(
            old_name='FixArm',
            new_name='Arm2800',
        ),
    ]
