# Generated by Django 2.2.12 on 2021-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210316_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arm2300',
            old_name='konevaiheen_ptuus',
            new_name='konevaiheen_pituus',
        ),
        migrations.RenameField(
            model_name='arm2800',
            old_name='konevaiheen_ptuus',
            new_name='konevaiheen_pituus',
        ),
        migrations.AddField(
            model_name='arm2300',
            name='kaksi',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='arm2800',
            name='kaksi',
            field=models.NullBooleanField(),
        ),
    ]
