# Generated by Django 2.2.12 on 2021-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210316_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm2300',
            name='kaksi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arm2800',
            name='kaksi',
            field=models.BooleanField(default=False),
        ),
    ]
