# Generated by Django 2.2.12 on 2021-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210316_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aika', models.TimeField()),
                ('kuvaus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=15)),
                ('aloitusindeksi', models.PositiveIntegerField()),
                ('kaynnistysaika', models.TimeField()),
            ],
        ),
    ]
