# Generated by Django 2.2.12 on 2021-03-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_apu_kone'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm2800',
            name='odotusvaiheen_pituus',
            field=models.PositiveIntegerField(default=600),
            preserve_default=False,
        ),
    ]
