# Generated by Django 2.2.12 on 2021-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_arm2300_konevaiheen_pituus'),
    ]

    operations = [
        migrations.AddField(
            model_name='kone',
            name='siirtyman_kesto',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
