# Generated by Django 2.2.12 on 2021-03-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_kone_siirtyman_kesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arm2300',
            old_name='purkuvaiheen_pituus',
            new_name='vaiheen_pituus',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
