# Generated by Django 2.2.12 on 2021-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210326_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='arm2800',
            name='jaahdytysvaiheen_pituus',
            field=models.PositiveIntegerField(default=960),
            preserve_default=False,
        ),
    ]
